repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

      - id: terraform_docs
        name: terraform_docs_modules
        args:
          - --args=--config=./.terraform-docs.yml
